# Generated by Django 5.1.4 on 2024-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ambient_temperature', models.FloatField()),
                ('thermostat_target_temperature', models.FloatField()),
                ('thermostat_current_temperature', models.FloatField()),
            ],
        ),
    ]
