# Generated by Django 5.1.4 on 2024-12-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loginpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetry',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
