# Generated by Django 5.1.4 on 2025-01-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='d_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
