# Generated by Django 5.1.4 on 2025-01-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_telemetry_d_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='mode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
