# Generated by Django 5.1.4 on 2025-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_telemetry_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='values_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='d_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='mode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
